package xboxkeybinder;

public enum XboxKeys {
NULL, BACK, BUTTON_A, BUTTON_B, BUTTON_X, BUTTON_Y, LEFT_SHOULDER, LEFT_THUMB, RIGHT_SHOULDER, RIGHT_THUMB, START, DPAD, DPAD_DIRECTION, LEFT_THUMB_MAGNITUDE, LEFT_THUMB_DIRECTION, RIGHT_THUMB_DIRECTION, RIGHT_THUMB_MAGNITUDE, RIGHT_TRIGGER_MAGNITUDE, LEFT_TRIGGER_MAGNITUDE
};
